name: cd

on:
  push:
    branches: [main]

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: "1.23.0"

    - name: Set up Goose
      uses: mscno/setup-goose@v1

    - name: Build binary
      run: bash scripts/buildprod.sh

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'
    
    - name: Create docker image and push to GCP
      run: gcloud builds submit --tag asia-southeast1-docker.pkg.dev/notely-459508/notely-ar-repo/notely:latest .

    - name: Install goose
      run: 
    - name: Database migration
      run: |
        source .env
        cd sql/schema
        goose turso $DATABASE_URL up
        cd ..
        cd ..

    - name: Deploy to Cloud Run
      run: gcloud run deploy notely --image asia-southeast1-docker.pkg.dev/notely-459508/notely-ar-repo/notely:latest --region asia-southeast1 --allow-unauthenticated --project notely-459508 --max-instances=4
